pyproject.toml

I don't normally use `pyproject.toml`-only builds, so I have no idea what I'm doing.

Fixes for pyproject.toml install issues

---

.github/workflows/linting.yaml
.github/workflows/testing.yaml
archeryutils/__init__.py
archeryutils/classifications/__init__.py
archeryutils/classifications/classifications.py
archeryutils/handicaps/__init__.py
archeryutils/handicaps/handicap_equations.py
archeryutils/handicaps/handicap_functions.py
archeryutils/handicaps/tests/__init__.py
archeryutils/handicaps/tests/test_handicaps.py
archeryutils/load_rounds.py
archeryutils/rounds.py
archeryutils/targets.py
archeryutils/tests/__init__.py
archeryutils/tests/test_rounds.py
archeryutils/tests/test_targets.py
examples.py
pyproject.toml

Add continuous integration:
Separate yaml files for linting and testing.
Will close #20

Add Continuous Integration

---

archeryutils/classifications/agb_indoor_classifications.py
archeryutils/classifications/agb_old_indoor_classifications.py
archeryutils/classifications/agb_outdoor_classifications.py
archeryutils/handicaps/handicap_equations.py
archeryutils/handicaps/handicap_functions.py
archeryutils/handicaps/tests/test_handicaps.py
examples.ipynb

Closes #4 
Add `score_for_passes` function that can be called by `score_for_round` such that the latter now returns a single number which is more intuitive.
This is a Breaking Change implemented in preparation for first release.

Separate score for round and score for passes into two functions

---

archeryutils/constants.py
archeryutils/handicaps/tests/test_handicap_tables.py
archeryutils/handicaps/tests/test_handicaps.py
archeryutils/load_rounds.py
archeryutils/rounds.py
archeryutils/targets.py
archeryutils/tests/test_constants.py
archeryutils/tests/test_rounds.py
archeryutils/tests/test_targets.py
examples.ipynb
pyproject.toml

Closes #27 
Set default target diameter units to cm
Updates tests and load_rounds functionality
Round data files all seem to specify target face sizes in cm already so enforcing this as the default unit makes sense.
Aliases for distance units moved into the constants file as it was getting out of hand and avoiding repitition, choice of conversion constants handled in the branching points in `Target.__init__`, this could perhaps be handled more elegantly if more units need to be supported in the future but didn't want to change more than necessary for now.

Targetdiameter

---

archeryutils/__init__.py
archeryutils/classifications/__init__.py
archeryutils/classifications/agb_field_classifications.py
archeryutils/classifications/agb_indoor_classifications.py
archeryutils/classifications/agb_old_indoor_classifications.py
archeryutils/classifications/agb_outdoor_classifications.py
archeryutils/classifications/classification_utils.py
archeryutils/classifications/tests/test_agb_field.py
archeryutils/classifications/tests/test_agb_indoor.py
archeryutils/classifications/tests/test_agb_old_indoor.py
archeryutils/classifications/tests/test_agb_outdoor.py
archeryutils/classifications/tests/test_classification_utils.py
archeryutils/handicaps/handicap_equations.py
archeryutils/handicaps/handicap_functions.py
archeryutils/handicaps/tests/test_handicap_tables.py
archeryutils/handicaps/tests/test_handicaps.py
archeryutils/load_rounds.py
archeryutils/round_data_files/AGB_indoor.json
archeryutils/rounds.py
archeryutils/targets.py
archeryutils/tests/test_rounds.py
archeryutils/tests/test_targets.py
examples.ipynb
pyproject.toml

Closes #53 
As raised by @TomHall2020 in #52 this simplifies and improves the method for setting units for distances and diameters.

Handle distance and diameter units in a better way

---

archeryutils/__init__.py
examples.ipynb

Closes #3 
As proposed by @LiamPattinson it would simplify things if a few choice items are added to the top level namespace of _archeryutils_.
This PR adds the `Target`, `Pass`, and `Round` classes to `archeryutils/__init__.py`.
I think keeping handicaps and classifications as explicit imports is sensible as users either want these or not, and they are somewhat distinct.

Add Target, Pass, and Round to top level namespace.

---

archeryutils/classifications/agb_field_classifications.py
archeryutils/classifications/agb_indoor_classifications.py
archeryutils/classifications/agb_old_indoor_classifications.py
archeryutils/classifications/agb_outdoor_classifications.py
archeryutils/classifications/classification_utils.py
archeryutils/classifications/tests/test_agb_field.py
archeryutils/classifications/tests/test_agb_indoor.py
archeryutils/classifications/tests/test_agb_old_indoor.py
archeryutils/classifications/tests/test_agb_outdoor.py
archeryutils/handicaps/handicap_equations.py
archeryutils/handicaps/handicap_functions.py
archeryutils/handicaps/tests/test_handicaps.py
archeryutils/load_rounds.py
archeryutils/rounds.py
archeryutils/targets.py
archeryutils/tests/test_rounds.py
archeryutils/tests/test_targets.py
docs/conf.py
examples.ipynb
pyproject.toml

Closes #61 
Should be compatible with python 3.9+ syntax. In order of increasing intensity:
- Replaced Dict, Tuple, List etc.
- Use type variable in handicap equations to show when floats or arrays are given as input and are returned as output
- type hints for fixed dictionaries for AGB classification data that are read from JSON
- enforce correct scoring systems for target class using literal types.
The sum of the last three points allow for removing some of the extra assertions that were in place just to please mypy, especially in the score_for_round functions.
There are still a couple of Anys floating around that I might be able to excise, but this feels like most of it, and enough that I could do with a check over to see if anything else needs included in this one.
On the topic of …

Typing Improvements

---

archeryutils/handicaps/handicap_scheme.py

Fix for #75
- Changes algorithm in `get_max_score_handicap` to take coarse and then fine steps.
- Refactors code for readability and less local variables
- ~Also fix missing default None parameter for arrow diameter~
- this was implemented already duriung #78 
- Only site that calls this function (`handicap_from_score`) and the main function that this calls (`score_for_round`) both have default None on the arrow diameter parameter so it hasn't mattered but fixed for consistency with those functions when debugging/calling it directly

Test speed

---

archeryutils/handicaps/handicap_scheme.py
archeryutils/handicaps/tests/test_handicaps.py

Fixes #85.
Incorrect ranges in the definition of the WA Field scoring system making targets (and therefore predicted scores) too large.
Spotted by @TomHall2020.

BugFix: definition of the WA Field scoring system.

---

archeryutils/rounds.py
archeryutils/tests/test_rounds.py

Closes #57 
- Added a check to raise `ValueError` if empty iterable is passed to `Round` constructor.
- Also added some guards against `archeryutils` types passed to constructors.
Checklist:

Prevent empty Round passes and type guarding

---

.github/workflows/coverage.yaml
.github/workflows/linting.yaml
.github/workflows/testing.yaml
README.md
archeryutils/classifications/agb_field_classifications.py
archeryutils/classifications/agb_indoor_classifications.py
archeryutils/classifications/agb_old_indoor_classifications.py
archeryutils/handicaps/handicap_scheme.py
archeryutils/targets.py
docs/getting-started/installation.rst
pyproject.toml

Closes #71 
- Raises minimum python version to 3.10 as discussed in #71 
- Also adds testing using latest python 3.12 and uses 3.12 for linting/coverage
- Updates github workflows to latest versions
Checklist:

Update Python Versions

---

archeryutils/classifications/tests/test_agb_field.py
archeryutils/classifications/tests/test_agb_indoor.py
archeryutils/classifications/tests/test_agb_old_indoor.py
archeryutils/classifications/tests/test_agb_outdoor.py
archeryutils/classifications/tests/test_classification_utils.py
archeryutils/handicaps/tests/test_handicap_tables.py
archeryutils/handicaps/tests/test_handicaps.py
archeryutils/tests/test_length.py
archeryutils/tests/test_rounds.py
archeryutils/tests/test_targets.py

Closes #83 by removing lists of methods from the testing function.
Users can now instead scroll down the class to see implemented tests and not worry about keeping the master list up to date.
As we move towards release it is assumed future tests will be written to cover any new code, and checked at review.

Clean method lists

---

archeryutils/tests/test_length.py
archeryutils/tests/test_targets.py

Add pytest approx to float comparisons in tests where not currently used and it makes sense to do so.
Closes #93 
Pytest `approx` or `allclose` is in use in most places, but I have had a check through and added a couple more where it might be appropriate.
There are still some instances where it does not make sense (as @LiamPattinson notes in #93) which have been left.
If any further have been missed we can review them should they raise problems in future, but this can hopefully close #93.

Add pytest approx to float comparisons in tests

---

archeryutils/classifications/classification_utils.py
archeryutils/classifications/tests/test_agb_field.py
archeryutils/classifications/tests/test_agb_indoor.py
archeryutils/classifications/tests/test_agb_outdoor.py
archeryutils/classifications/tests/test_classification_utils.py

Closes #98 
Preparation for field.
Includes test (well adding an additional option to existing test to check).

Update groupname generation in classifications to handle English Longbow as a synonym for Longbow.

---

.github/workflows/coverage.yaml

Use token from secrets to fix failure to upload.
Set to fail if any coverage errors in upload - poor default behaviour.
Boost to use python 3.13

Update coverage workflow.

---

archeryutils/classifications/agb_field_classifications.py
archeryutils/classifications/tests/test_agb_field.py

Due to a lack of specific tests a last minute bug crept in to #46 whereby shorter peg rounds were not restricted to Archery classification , but instead had values returned for all classifications.
This patch rectifies that, and introduces tests explicitly for this that were previously missing.

Bugfix: Restrict shorter peg rounds to Archery tier as per the rules in the new 2025 field classifications.

---

archeryutils/handicaps/handicap_scheme.py

Fixes #108 
Fixes an issue that resulted in division by zero in the rootfinding algorithm
This occurred when the score for which a handicap is requested is the same number of points below the maximum score for a round as one of the arbitrary bounds used to initialise the search interval.
Not a bug per-se, as the algorithm is robust enough to handle division by zero and select a better interval to return the 'correct' handicap, but resulted in a warniong being printed to the repl or stdout.
This is resolved by replacing the zero with a small number (xtol already in the function) when it occurs.
Returned handicaps may now be different in this instance by the 6th sig fig point, but this is within the tolerance that archeryutils purports to give and all tests still pass.

Fixes an issue that resulted in division by zero in the rootfinding algorithm

---

archeryutils/classifications/__init__.py
archeryutils/classifications/agb_old_field_classifications.py
archeryutils/classifications/tests/test_agb_field.py
archeryutils/classifications/tests/test_agb_old_field.py

To be consistent with old indoor classification naming.

Update old field classification naming

---

archeryutils/rounds.py
archeryutils/tests/test_rounds.py
docs/develop/whats-new.rst

Adds `n_arrows` attribute to rounds as inexpensive and useful to be exposed at the top level rather than calculated from `passes`.

Round narrows

---

archeryutils/classifications/agb_field_classifications.py
archeryutils/classifications/agb_indoor_classifications.py
archeryutils/classifications/agb_outdoor_classifications.py
archeryutils/classifications/classification_utils.py

As discussed in #103, the classification data generation functions can be unindented quite nicely by replacing direct iteration over bowstyle/gender/age divisions with the itertools product of those.
Implementing that was very straightforward, but while I was in there I did smell an opportunity to excise another bit of looping, where the class handicap thresholds and minimum distances themselves are built up by manual iteration over the indecies of the classification labels. That took a bit more effort, but I think is much more explicit this way, and the result is that the loop building up the classification data is now pretty much solely packaging things nicely, and has a minimum of inline logic. 
Inside the agb_outdoor `_assign_min_dist` function I could come up with various ways to …

Data looping in classification dict generation functions

---

.readthedocs.yaml
docs/conf.py
pyproject.toml

See: https://github.com/sphinx-doc/sphinx/issues/13362 and https://github.com/tox-dev/sphinx-autodoc-typehints/issues/523

Pin sphinx at <2.8.0 due to known issues.

---

archeryutils/round_data_files/AGB_outdoor_metric.json
docs/develop/whats-new.rst

Adds new AGB900 rounds as per https://archerygb.org/news/new-round-created-for-the-2025-junior-national-outdoor-championships
Listed from 70 down to 30 in AGB Metric outdoor rounds.

Add new AGB900 rounds.

---

archeryutils/classifications/agb_old_indoor_classifications.py
archeryutils/handicaps/__init__.py
archeryutils/handicaps/handicap_functions.py
archeryutils/handicaps/handicap_scheme.py
archeryutils/handicaps/handicap_scheme_aa.py
archeryutils/handicaps/handicap_scheme_agb.py
archeryutils/handicaps/handicap_tables.py
archeryutils/handicaps/tests/test_handicap_tables.py
archeryutils/handicaps/tests/test_handicaps.py
docs/develop/whats-new.rst

Use numpy typing closer to intended use as suggested by @LiamPattinson in #130
Take inputs to functions as `ArrayLike`, casting using `np.asarray()` where appropriate.
Return items as `NDArray[float64]` with single values being duck-typed in the majority of cases.
Removes the `FloatArray` type to just use `NDArray[float64]` explicitly.
Resolves a number of issues seen in latest mypy in a more sensible manner than #130 
Also allows us to simplify some of the "type-checker" appeasement throughout the code e.g. castings and overloads.

Update type checking to use numpy NDArray and ArrayLike

---

archeryutils/load_rounds.py
archeryutils/rounds.py

This change allows the rounds to "self identify" in a machine readable format. Applications can therefore take CSVs or JSON data and look up the identified round.
This extracts the "non-Django" bit out of #125

Store codename of the round on the object itself.
